### ISSUE TITLE
Ny Teknisk brukerstøtte

### ISSUE THREAD

**Issue by aas-tbuar** [Altinn/team-kunde#3]
Beskrivelse:

Det skal etableres en effektiv teknisk brukerstøtte for Altinn som sikrer at alle saker, bestilling av tilganger, hendelser og andre henvendelser fra tjenesteeiere og sluttbrukerststemleverandører kommer til riktig team og blir håndtert i henhold til avtaler. Gjennom en veldefinert prosess og riktig ressursallokering vil brukerstøtteteamet kunne håndtere henvendelser effektivt og sikre en smidig og rask løsning.

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/kunde/issues/21
- [ ] https://github.com/Altinn/kunde/issues/29
- [ ] https://github.com/Altinn/kunde/issues/28
- [ ] https://github.com/Altinn/kunde/issues/4
- [ ] Oversikt over avhengigheter til andre team
- [ ] https://github.com/Altinn/kunde/issues/6
- [ ] https://github.com/Altinn/kunde/issues/7
- [ ] https://github.com/Altinn/kunde/issues/8
- [ ] https://github.com/Altinn/kunde/issues/9
- [ ] https://github.com/Altinn/kunde/issues/5
- [ ] https://github.com/Altinn/kunde/issues/10
- [ ] https://github.com/Altinn/kunde/issues/58
```

Mål:

* Utvikle en effektiv teknisk brukerstøtte for Altinn som sikrer riktig tildeling av saker til DevOps-team.
* Øke effektiviteten og kvaliteten på brukerstøttetjenesten for å sikre en smidig og rask løsning av henvendelser fra tjenesteeiere og leverandører.
* Oppnå høy kundetilfredshet gjennom klare retningslinjer, rask respons og kompetent brukerstøtte.

Avhengigheter:

* Samarbeid med relevante DevOps-team for å sikre korrekt tildeling av saker.
* Tilgang til nødvendig opplæring og ressurser for brukerstøttepersonell.
* Implementering av passende tekniske løsninger og verktøy for håndtering av brukerstøtteprosessen.

**Comment by OleGunnarHoddo** [comment]
Vi jobber for tiden med å se på hvordan supportapparatet for Altinn skal være fremover og etter at Altinn 2 skrus av.  I den anledning ønsker vi å snakke med de ulike produktteamene og forstå bedre hvordan dette fungerer i dag og hvordan vi best kan få på plass en profesjonell supportorganisasjon som ivaretar sluttbrukere og kunder (tjenesteeiere) på en best mulig måte.

hva fungerer bra?
hva kan bli bedre?
hva fungerer overhodet ikke?

- [ ] Møte Autoriasjon med R.Tafjord/E.Kørra 05.02.25
